### ISSUE TITLE
Consider merging type implementation and in-memory/serialization into one thing

### ISSUE THREAD

**Issue by badboy** [badboy/glean.rs#14]
Right now type implementations only direct their stuff to the storage (relying on bincode or other serialization).
The loading and then serialization to json are implemented on the enum:

https://github.com/badboy/glean.rs/blob/094390e7030f402be0f8b60caca3b6d98f3a1b2c/glean-core/src/metrics/mod.rs

This means adding a new metric needs a new file for the implementation, entries in the mentioned enum and implementing the category and serialization.
Maybe we can move category and json-serialization into the type directly?

**Comment by Dexterp37** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1551143
